### ISSUE TITLE
CUDA out of memory. Tried to allocate 462.00 MiB. GPU

### ISSUE THREAD

**Issue by liuzhenghua** [neuralmagic/AutoFP8#15]
using the following code to quantize Qwen2-72B-Instruct with 4 * L20(48GB):
```python
from auto_fp8 import AutoFP8ForCausalLM, BaseQuantizeConfig

pretrained_model_dir = "/data/modelscope/qwen/Qwen2-72B-Instruct"
quantized_model_dir = "/data/modelscope/qwen/Qwen2-72B-FP8-Instruct"

# Define quantization config with static activation scales
quantize_config = BaseQuantizeConfig(quant_method="fp8", activation_scheme="dynamic")
# For dynamic activation scales, there is no need for calbration examples
examples = []

# Load the model, quantize, and save checkpoint
model = AutoFP8ForCausalLM.from_pretrained(pretrained_model_dir, quantize_config)
model.quantize(examples)
model.save_quantized(quantized_model_dir)
```
![image](https://github.com/neuralmagic/AutoFP8/assets/11787325/e16ba004-d733-42d6-b351-ea9a1fcd4045)

**Comment by mgoin** [comment]
Hi @liuzhenghua thanks for raising this issue, please try updating your main branch as this PR should fix your issue! https://github.com/neuralmagic/AutoFP8/pull/16

**Comment by liuzhenghua** [comment]
> Hi @liuzhenghua thanks for raising this issue, please try updating your main branch as this PR should fix your issue! #16
Hi @mgoin  thanks for resovling this problem.
The issue of gpu memory not being released in a timely has been resolved. 
The new code can now quantize the qwen2-72b-instruct model on 4 * L20, but the output is garbled and incorrect. In the old version, I was able to quantize qwen2-72b-instruct on 8 * L20, and the output was perfectly fine.
![image](https://github.com/neuralmagic/AutoFP8/assets/11787325/3442967a-75df-4f82-af6d-c697f84c4bb1)

**Comment by liuzhenghua** [comment]
he output is correct when using commit ID 6137606349d43f078f3b8f1ce7ac56bd35ed3c8e. Initially, I attempted to quantize the qwen-72b-instruct model using 4 * L20 GPUs, but encountered a CUDA out of memory error. Subsequently, I successfully quantized it using 8 * L20 GPUs, and it worked perfectly.

The latest code can quantize the qwen-72b-instruct model with 4 * L20 GPUs, but the resulting output is meaningless.

**Comment by liuzhenghua** [comment]
The output is correct when using commit ID https://github.com/neuralmagic/AutoFP8/commit/6137606349d43f078f3b8f1ce7ac56bd35ed3c8e. Initially, I attempted to quantize the qwen-72b-instruct model using 4 * L20 GPUs, but encountered a CUDA out of memory error. Subsequently, I successfully quantized it using 8 * L20 GPUs, and it worked perfectly.

The latest code can quantize the qwen-72b-instruct model with 4 * L20 GPUs, but the resulting output is meaningless.

**Comment by mgoin** [comment]
Thanks for reporting @liuzhenghua , I am working on trying to reproduce dynamic quantization of that model now. FYI we have a statically quantized checkpoint with verified accuracy in vLLM here https://huggingface.co/neuralmagic/Qwen2-72B-Instruct-FP8

**Comment by mgoin** [comment]
Hi @liuzhenghua I really appreciate you pointing out this issue. In the above PR, I diagnosed that it was an issue with the bias tensors are being incorrectly copied from the original modules. With the fix, I seem to be able to produce accurate `Qwen2-72B-Instruct-FP8-dynamic`

Code to produce model:
```
from auto_fp8 import AutoFP8ForCausalLM, BaseQuantizeConfig

pretrained_model_dir = "Qwen/Qwen2-72B-Instruct"
quantized_model_dir = "Qwen2-72B-Instruct-FP8-dynamic"

# Define quantization config with static activation scales
quantize_config = BaseQuantizeConfig(quant_method="fp8", activation_scheme="dynamic")
# For dynamic activation scales, there is no need for calbration examples
examples = []

# Load the model, quantize, and save checkpoint
model = AutoFP8ForCausalLM.from_pretrained(pretrained_model_dir, quantize_config)
model.quantize(examples)
model.save_quantized(quantized_model_dir)
```

Usage:
```
>>> from vllm import LLM
>>> model = LLM("Qwen2-72B-Instruct-FP8-dynamic", tensor_parallel_size=4)
>>> model.generate("Write an algorithm for quick sort")[0].outputs[0].text
Processed prompts: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.56it/s, Generation Speed: 40.96 toks/s]

' to sort a given array.\n\nInputs: [10, 80,'
```

**Comment by liuzhenghua** [comment]
> Hi @liuzhenghua I really appreciate you pointing out this issue. In the above PR, I diagnosed that it was an issue with the bias tensors are being incorrectly copied from the original modules. With the fix, I seem to be able to produce accurate `Qwen2-72B-Instruct-FP8-dynamic`
> 
> Code to produce model:
> 
> ```
> from auto_fp8 import AutoFP8ForCausalLM, BaseQuantizeConfig
> 
> pretrained_model_dir = "Qwen/Qwen2-72B-Instruct"
> quantized_model_dir = "Qwen2-72B-Instruct-FP8-dynamic"
> 
> # Define quantization config with static activation scales
> quantize_config = BaseQuantizeConfig(quant_method="fp8", activation_scheme="dynamic")
> # For dynamic activation scales, there is no need for calbration examples
> examples = []
> 
> # Load the model, quantize, and save checkpoint
> model = AutoFP8ForCausalLM.from_pretrained(pretrained_model_dir, quantize_config)
> model.quantize(examples)
> model.save_quantized(quantized_model_dir)
> ```
> 
> Usage:
> 
> ```
> >>> from vllm import LLM
> >>> model = LLM("Qwen2-72B-Instruct-FP8-dynamic", tensor_parallel_size=4)
> >>> model.generate("Write an algorithm for quick sort")[0].outputs[0].text
> Processed prompts: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.56it/s, Generation Speed: 40.96 toks/s]
> 
> ' to sort a given array.\n\nInputs: [10, 80,'
> ```

I tested the new version, and the output is now working fine. Thank you very much.
